Repository managarm/mlibc, pull requests merged in 2024-08, with the labels that each got.

#1099 options/posix: Stub jrand48
  options/posix/generic/posix_stdlib.cpp
  options/posix/include/bits/posix/posix_stdlib.h
Labels: enhancement

#1094 Some self-hosting fixes for Managarm
  sysdeps/managarm/generic/file.cpp
  sysdeps/managarm/generic/ioctl.cpp
Labels: bugfix

#1095 Several additions for VLC
  abis/linux/in.h
  options/ansi/include/inttypes.h
  options/posix/generic/posix_stdio.cpp
  options/posix/generic/posix_string.cpp
  options/posix/include/bits/posix/posix_stdio.h
  options/posix/include/bits/posix/posix_string.h
  sysdeps/managarm/generic/socket.cpp
Labels: enhancement

#1104 options/ansi: Handle binary specifiers in format strings
  options/ansi/generic/stdio-stubs.cpp
  options/internal/include/mlibc/strtol.hpp
  tests/ansi/sprintf.c
  tests/ansi/sscanf.c
  tests/ansi/strtol.c
Labels: enhancement, bugfix
