Repository managarm/mlibc, pull requests merged in 2024-02, with the labels that each got.

#1002 options/posix: Implement waitid
  options/posix/generic/sys-wait-stubs.cpp
  options/posix/include/mlibc/posix-sysdeps.hpp
  sysdeps/linux/generic/sysdeps.cpp
  sysdeps/managarm/generic/fork-exec.cpp
  tests/meson.build
  tests/posix/waitid.c
Labels: enhancement, unimplemented

#1014 ci: add managarm sysdep test
  .github/workflows/ci.yml
  ci/managarm.cross-file
  tests/meson.build
Labels: enhancement

#989 Generate rust bindings from mlibc headers
  options/ansi/generic/stdio-stubs.cpp
  options/ansi/include/stdio.h
  options/posix/generic/posix_time.cpp
  options/posix/include/bits/posix/posix_time.h
  options/posix/include/dlfcn.h
  options/posix/include/glob.h
  options/posix/include/termios.h
  scripts/rust-libc-config.yml
  scripts/rust-libc-header.rs
  scripts/rust-libc.py
Labels: bug, enhancement, affects ABI
